version: '3'

services:
  mysql:
    container_name: compass_ecommerce_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - compass_network

networks:
  compass_network:
