server:
  port: 8090
  undertow:
    threads:
      worker: 24
      io: 2

#spring:
 # redis:
  #  host: localhost
   # port: 6379
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

mysql:
  username: root
  password: 123456
  schema: ecommerce
  url: localhost:3306

jwt:
  secret: mysecret