server:
  port: 8090
  undertow:
    threads:
      worker: 24
      io: 2

springdoc:
  swagger-ui:
    path=/swagger-ui:
      html:
mysql:
  username: root
  password: 123456
  schema: ecommerce
  url: localhost:3306